import { eq, and } from "drizzle-orm";
import { db } from "@/db";
import { automaticGiftRules, items } from "@/db/schema";
import { addItemToInventory, getArsenalCount, ARSENAL_CAPACITY } from "@/lib/shops";
import { createNotification } from "@/lib/notifications";

export type GiftTrigger = "birthday"; // extend here as more triggers are added

async function getActiveGiftRulesForTrigger(trigger: GiftTrigger) {
  return db
    .select({
      id: automaticGiftRules.id,
      itemId: automaticGiftRules.itemId,
      quantity: automaticGiftRules.quantity,
      senderLabel: automaticGiftRules.senderLabel,
      message: automaticGiftRules.message,
      itemName: items.name,
    })
    .from(automaticGiftRules)
    .innerJoin(items, eq(automaticGiftRules.itemId, items.id))
    .where(and(eq(automaticGiftRules.trigger, trigger), eq(automaticGiftRules.isActive, true)));
}

/**
 * Fires every active rule configured for a trigger, for one character —
 * e.g. every birthday-triggered gift rule, for the character whose
 * birthday just happened. Not tied to any sending character's own
 * inventory; these are generated by the system. Silently skips a rule if
 * the recipient's arsenal is already full for that item, rather than
 * failing — there's no one to show an error to in an automated process.
 */
export async function fireGiftTrigger(trigger: GiftTrigger, characterId: number): Promise<void> {
  const rules = await getActiveGiftRulesForTrigger(trigger);
  if (rules.length === 0) return;

  const arsenalCount = await getArsenalCount(characterId);
  if (arsenalCount >= ARSENAL_CAPACITY) return;

  for (const rule of rules) {
    await addItemToInventory(characterId, rule.itemId, rule.quantity);

    const itemLabel = rule.quantity > 1 ? `${rule.quantity}x ${rule.itemName}` : rule.itemName;
    const notifMessage = rule.message
      ? `${rule.senderLabel} sent you ${itemLabel}: "${rule.message}"`
      : `${rule.senderLabel} sent you ${itemLabel}`;

    await createNotification(characterId, "item_gifted", notifMessage, "/characters");
  }
}
